# Patches specific to this repo

# Container App name
- op: replace
  path: /name
  value: ca-patient

# Container App env id
- op: replace
  path: /properties/managedEnvironmentId
  value: /subscriptions/2da318e2-604b-4f60-8984-b801b824a602/resourceGroups/rg-platform/providers/Microsoft.App/managedEnvironments/cae-platform

# Managed Identity
- op: add
  path: /
  value:
    identity:
      type: UserAssigned
      userAssignedIdentities:
        ? /subscriptions/2da318e2-604b-4f60-8984-b801b824a602/resourceGroups/rg-platform/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platform
        : {}

# container name
- op: replace
  path: /properties/template/containers/0/name
  value: patient

# env vars
- op: add
  path: /properties/template/containers/0/env
  value:
    - name: MONGO_URI
      secretRef: mongo-uri
